package org.openjdbcproxy.grpc.dto;

public enum ParameterType {
    NULL, BOOLEAN, BYTE, SHORT, INT, LONG, FLOAT, DOUBLE, BIG_DECIMAL, STRING, BYTES, DATE, TIME, TIMESTAMP, ASCII_STREAM,
    UNICODE_STREAM, BINARY_STREAM, OBJECT, CHARACTER_READER, REF, BLOB, CLOB, ARRAY, URL, ROW_ID, N_STRING, N_CHARACTER_STREAM,
    N_CLOB, SQL_XML,
}
